//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.26 at 07:38:14 PM IST 
//


package com.agecalculator.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ageinyear" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ageinmonths" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ageinweeks" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ageindays" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ageinhours" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ageinminutes" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ageinseconds" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="minmajor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataList", propOrder = {
    "ageinyear",
    "ageinmonths",
    "ageinweeks",
    "ageindays",
    "ageinhours",
    "ageinminutes",
    "ageinseconds",
    "name",
    "minmajor"
})
public class DataList {

    @XmlElement(required = true)
    protected String ageinyear;
    @XmlElement(required = true)
    protected String ageinmonths;
    @XmlElement(required = true)
    protected String ageinweeks;
    @XmlElement(required = true)
    protected String ageindays;
    @XmlElement(required = true)
    protected String ageinhours;
    @XmlElement(required = true)
    protected String ageinminutes;
    @XmlElement(required = true)
    protected String ageinseconds;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String minmajor;

    /**
     * Gets the value of the ageinyear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeinyear() {
        return ageinyear;
    }

    /**
     * Sets the value of the ageinyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeinyear(String value) {
        this.ageinyear = value;
    }

    /**
     * Gets the value of the ageinmonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeinmonths() {
        return ageinmonths;
    }

    /**
     * Sets the value of the ageinmonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeinmonths(String value) {
        this.ageinmonths = value;
    }

    /**
     * Gets the value of the ageinweeks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeinweeks() {
        return ageinweeks;
    }

    /**
     * Sets the value of the ageinweeks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeinweeks(String value) {
        this.ageinweeks = value;
    }

    /**
     * Gets the value of the ageindays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeindays() {
        return ageindays;
    }

    /**
     * Sets the value of the ageindays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeindays(String value) {
        this.ageindays = value;
    }

    /**
     * Gets the value of the ageinhours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeinhours() {
        return ageinhours;
    }

    /**
     * Sets the value of the ageinhours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeinhours(String value) {
        this.ageinhours = value;
    }

    /**
     * Gets the value of the ageinminutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeinminutes() {
        return ageinminutes;
    }

    /**
     * Sets the value of the ageinminutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeinminutes(String value) {
        this.ageinminutes = value;
    }

    /**
     * Gets the value of the ageinseconds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeinseconds() {
        return ageinseconds;
    }

    /**
     * Sets the value of the ageinseconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeinseconds(String value) {
        this.ageinseconds = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the minmajor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinmajor() {
        return minmajor;
    }

    /**
     * Sets the value of the minmajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinmajor(String value) {
        this.minmajor = value;
    }

}
