//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.26 at 07:38:14 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ashok.com/xml/agecalculator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.agecalculator.stub;
