//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 10:20:38 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ashok.com/xml/agecalculator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ashok.xml.agecalculator;
